### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/reproschema-ui#147]
As I am working on the readme for this, by reinjecting some of my own ~~doc~~ notes and some of the content of other issues (#133 #4 #18) I realize that this does not have a license.

Should I add one in the `[DOC]` PR I am working on? Apache 2.0 like for the reproschema?

**Comment by satra** [comment]
thanks @Remi-Gau - added the LICENSE file - a lot easier to do through the github interface.
