### ISSUE TITLE
Placing of the next item in an activity

### ISSUE THREAD

**Issue by danielmlow** [ReproNim/reproschema-ui#171]
when I proceed to a new question, the new question appears at the top of the screen, but I am not automatically brought to the top of the screen, and I imagine participants may not automatically think to scroll up. 

But also in most recording settings the record/stop/play icon is at the bottom but the next item appears on top. there is a bit of disconnect here. 

So I suggest we 1) place next items at the bottom and 2) have reproschema scroll down a bit automatically. 

Thanks!

**Comment by sanuann** [comment]
I've solved this problem by making the screen to auto-scroll to the top of the screen so that the next question is visible.
