### ISSUE TITLE
Nested activities

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/reproschema-ui#176]
Reproschema supports nested activities but I made a quick test last weekend and it does not seem that this is supported by the UI.

I might be wrong. Will try to provide a MWE to show the "problem" I encountered.

**Comment by sanuann** [comment]
please post an MWE. you can check an example here: https://github.com/ReproNim/demo-protocol/blob/master/activities/Screening/Screening_schema
(the present way it is implemented isn't current perhaps. I will discuss with satra and get back to you)
