### ISSUE TITLE
fix export and submit options

### ISSUE THREAD

**Issue by sanuann** [ReproNim/reproschema-ui#195]
the submit option should only appear if the url has the right parameters, while the export option should appear if the submit capability is not there.

**Comment by satra** [comment]
> while the export option should appear if the submit capability is not there.

or is enabled in the protocol

**Comment by sanuann** [comment]
> > while the export option should appear if the submit capability is not there.
> 
> or is enabled in the protocol

do we want the export option enabled in covid19 protocol? daniel said export isn't needed for the covid19 study so I removed it

**Comment by satra** [comment]
we can remove from the protocol for now.
