### ISSUE TITLE
Submitting data during the protocol

### ISSUE THREAD

**Issue by danielmlow** [ReproNim/reproschema-ui#249]
@satra, @sanuann, now that we're doing longer assessments, it would be good to submit data can we submit data before the end in case someone abandonds the protocol we can still collect some of the data. So we could:
a) every time someone clicks on "submit" (this can happen within activities) or 
b) at the end of each activity

any thoughts?

**Comment by sanuann** [comment]
yes, probably "upload" can be done when the participant hits "next" after each activity?

**Comment by danielmlow** [comment]
@satra , any preferences?

**Comment by satra** [comment]
only if this can be asynchronous. you don't really want them to wait. i don't mind multiple uploads on the server side.

**Comment by danielmlow** [comment]
Great, @sanuann can we submit data when participant clicks "next" after each activity in an asynchronous manner so that they can continue submitting data?
