### ISSUE TITLE
Remove "Review responses"

### ISSUE THREAD

**Issue by danielmlow** [ReproNim/reproschema-ui#254]
@sanuann 

![image](https://user-images.githubusercontent.com/14787791/134980220-2d723564-e6c0-4b65-adba-abbc671e5721.png)

Change to "Click Next below:"

Thanks

**Comment by sanuann** [comment]
@danielmlow is this the spanish equivalent: luego haga click en Siguiente abajo

**Comment by danielmlow** [comment]
"Haga click en Siguiente para continuar:"
