### ISSUE TITLE
Change wording accordingly

### ISSUE THREAD

**Issue by danielmlow** [ReproNim/reproschema-ui#257]
Since we changed the content of the Export/Download button, we should change this accordingly:

https://github.com/ReproNim/reproschema-ui/blob/de5162d5ff6f6d6772bd01017c25c687840a84e1/src/locales/en.json#L30

It should say:

Please click "Finish" below to submit your responses. You can additionally click the "Download" button on sidebar if you wish to download a personal copy of your data.

**Comment by sanuann** [comment]
please also let me know the spanish equivalent. (or check the `locales/es/json` file if the current one is still ok)

**Comment by danielmlow** [comment]
Por favor haga click en "Finalizar" abajo para enviar sus respuestas. Adicionalmente puede hacer click en "Descargar" en el menú para descargar una copia personal de sus datos.
