### ISSUE TITLE
reproschema Workflow takes too long

### ISSUE THREAD

**Issue by danielmlow** [ReproNim/reproschema-ui#264]
@satra the current workflow takes around 2-3 minutes each time there is an update. Launching it is the only way to test how changes are implemented. 

"Build a multi-line script" is what takes most time, almost 2 minutes:
https://github.com/danielmlow/WellBeingStudy/blob/3583e43f25e3308cff14c43d6ec24fbb57cada4c/.github/workflows/build_deploy.yml#L53

![image](https://user-images.githubusercontent.com/14787791/135908395-8704034e-c158-4f21-a1ad-03d68d3c317a.png)

Is there any way to speed this up?  One could commit changes without running the workflow and seeing if it works? If it doesn't then running the workflow to see if it captures a trailing comma or something like that?

Anything else that can be loaded directly from the repo (instead of unzipping or using npm) or installed in some other way to speed things up?

**Comment by sanuann** [comment]
> Launching it is the only way to test how changes are implemented.

you can also view your protocol here (without updating the ui checksum in your study repo):
https://www.repronim.org/reproschema-ui/#/?url=https://raw.githubusercontent.com/danielmlow/WellBeingStudy/master/protocol/WellBeing_schema

**Comment by danielmlow** [comment]
ahaaa! Thank you

I say "ahaaa" in the following accent: https://www.youtube.com/watch?v=4ORMeSJsYIM&ab_channel=BigRick
