### ISSUE TITLE
testing local protocols

### ISSUE THREAD

**Issue by djarecka** [ReproNim/reproschema-ui#271]
The config file takes `githubSrc` to get schema. We should allow to load local schema to improve local development.

Right now, I understand that I have to push all changes to the schema to be able to see how it works wit `reproschema-ui`

**Comment by Remi-Gau** [comment]
If I were to add some doc how to serve local protocols (for testing or debugging) where would be the most "logical" place to have it.

- reproschema doc
- reproschema-py doc
- reproschema-ui doc

**Comment by satra** [comment]
@Remi-Gau - i would suggest to reproschema-doc and then pointing to the doc from the py and ui readme.

**Comment by Remi-Gau** [comment]
OK that was my hunch but I wanted confirmation.
