### ISSUE TITLE
[Time sensitive] It allows Next activity before current activity is finished

### ISSUE THREAD

**Issue by danielmlow** [ReproNim/reproschema-ui#290]
@satra @sanuann @djarecka 

The issue here is people (who might want to finish quick) can click Next and skip most of the Daily affect scale:
![image](https://user-images.githubusercontent.com/14787791/141710718-443512ab-12a3-44bc-9dc8-e15a8838bc7a.png)

This option should only be available when activity is complete. 

There are two items in this activity: a Daily Affect Scale and an open response question. The order is shuffled. The issue only happens when Open Response question comes first, letting people to skip (click Next) most of the Daily Affect Scale after they complete the first item. 

Here is the code that might be underlying this:
https://github.com/ReproNim/reproschema-ui/blob/ca1a2d782ede45bd4b6deb2625a937c33fbc793c/src/components/Survey/Survey.vue#L11

Note `&& currentActivityIndex < listShow.length"` was added in a commit (https://github.com/ReproNim/reproschema-ui/commit/ca1a2d782ede45bd4b6deb2625a937c33fbc793c#diff-dff757c16e7204e95bb15e06da8eee08971c0ba825493b0cfc8c2f5a5b0c282a) so that the next button and text does not appear on the last activity after submitting data (this was confusing). The effect of that commit should not be undone.

Here is the activity that is causing problems (note the `questions` param is a global param from the URL):
https://github.com/danielmlow/WellBeingStudy_daily/blob/040c18842c7e74cd6fbdc755a93ba34bfc85f0fa/activities/pre/pre_schema 

Here is a URL where this can be tested (click on the `pre` activity):
https://danielmlow.github.io/WellBeingStudy_daily/#/?auth_token=test-e7ee8a9f39354005ba931fabe26171a8&expiry_time=2021-11-21T12:22:37.610545+00:00&lang=en&questions=1&branch=meditationchoose&day=1&uid=en_9999

**Comment by djarecka** [comment]
@danielmlow - did it change after my recent changes, or it was like that before?

**Comment by danielmlow** [comment]
@djarecka Recent changes. it affects only certain activities like the one I'm showing.

**Comment by djarecka** [comment]
I don't see this when using your link:
<img width="1382" alt="Screen Shot 2021-11-15 at 9 33 27 AM" src="https://user-images.githubusercontent.com/1662746/141799620-37a32b36-b121-4f8c-a7c1-2cf872546576.png">

**Comment by djarecka** [comment]
ok, I could see it. Having very limited statistics, seems to me that it appears when the recording is the first item. Can you confirm this?

Was random order in the design? Do you want to keep it?

**Comment by danielmlow** [comment]
Correct, it appears when recording is first item.

The random order is needed, yes. 

Thanks!

**Comment by djarecka** [comment]
@danielmlow - I'm testing this thing locally by providing to my `repronim-ui` config file `https://raw.githubusercontent.com/danielmlow/WellBeingStudy_daily/master/protocol/WellBeing_schema`, but I'm often having problems with loading activity. Is it only for me, or do you experience the same?

**Comment by danielmlow** [comment]
yeah, in pre and post activity. setting "shuffle": false fixes it, so we may have to do that. see here:
https://github.com/ReproNim/reproschema-ui/issues/291

it doesn't fix this issue though.

**Comment by djarecka** [comment]
my issues was related to something else - didn't set proper parameters in  the link and I was getting unpredictable behavior...
But one I fixed that, I also saw that sometimes hangs without any errors... 

The original issue you reported here is not fixed by removing the shuffling, you can do it temporarily, but will try to fix it.

**Comment by djarecka** [comment]
@danielmlow - could you please check #293 I think it solves the next issue

**Comment by danielmlow** [comment]
@djarecka fixed thanks!!
