### ISSUE TITLE
[urgent] Save global parameter value to zip filename

### ISSUE THREAD

**Issue by danielmlow** [ReproNim/reproschema-ui#292]
@satra @sanuann @djarecka 

I need to send certain protocols depending on what people have completed. For that it would be ideal to have a global parameter `day` (1 through 28) in the filename of the completed assessment, so I can know what to send them. 

Right now we just have `uid` in the filename. How can we add something like `day-{day}` obtained similar to uid in the URL  

https://danielmlow.github.io/WellBeingStudy_daily/#/?auth_token=test-e7ee8a9f39354005ba931fabe26171a8&expiry_time=2021-11-21T12:22:37.610545+00:00&lang=en&questions=1&branch=meditationchoose&day=1&uid=en_9999

I think this is where it is added:
https://github.com/ReproNim/reproschema-ui/blob/8c5ca141a109ed3075b65c1da2691648e7fc8b16/src/components/Inputs/SaveData/SaveData.vue#L127

**Comment by danielmlow** [comment]
This is what the current output looks like.
![image](https://user-images.githubusercontent.com/14787791/141787061-d7fecd1a-f3e7-4ed7-87a9-8b03d134711d.png)

I would like to take the global parameter `day=N` for the URL and add `_dayN_` to the zip filename.

**Comment by satra** [comment]
we should try to not add things in the filename. is this information anywhere in the content of the file? that's more important? whether it's based on protocol or timestamp? otherwise this becomes a one-off thing not a general purpose approach.

**Comment by danielmlow** [comment]
Okay, the current hacky solution is to count the amount of submissions per user. It is possible the user clicks the button twice or edits response and resubmits which make the user skip a day. This doesn´t seem to happen at all, but may happen.

A better solution is to look at the URL within one of the jsons as you suggested, but I don´t think the full unique URL is saved in the jsons. Haven´t found it. 

Could you include the full URL in all jsons?

**Comment by satra** [comment]
the full url has sensitive info and given that we would likely not want it in the json. part of the challenge here is to use information that is generic. but also to see it through the lens of provenance. what are we missing in the outputs that doesn't allow you to track. if the parameter day is controlling an item, then that item should be in the response.

**Comment by satra** [comment]
the question then is whether `day` maps to a specific item, which would be required if you are using `day` as parameter. hence the `item` becomes synonymous with day.

**Comment by danielmlow** [comment]
In our study `day` is controlling a parameter. When `day > 14` then participants can choose a task. In that sense, we don't know what day they're on by looking at the task name. if we can save the `day` value in the json, that would be nice.

**Comment by satra** [comment]
but you know from analyzing their submissions, no? those have timestamps in them.

**Comment by danielmlow** [comment]
Yes. But when `day > 14` they can choose among 14 tasks, so there isn’t a one to one mapping. 

I can look at the timestamp to know which day they were on, but have to compute it. That’s probably the best solution for this study

**Comment by danielmlow** [comment]
The solution will be to calculate how many days they submitted from the timestamp in zip filename. It could be that they submit the same task twice and this would create an error which would make them skip a day, but this is unlikely.
