### ISSUE TITLE
any plans to merge all the dependabot alert PRs?

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/reproschema-ui#318]
just wondering. 😉

**Comment by yibeichan** [comment]
@satra i'm looking through all issues, wondering the same; should we merge those PRs?

**Comment by satra** [comment]
we don't have really good testing in place, so i would tag (not release) the current commmittish and then you could go through and merge them.

**Comment by yibeichan** [comment]
okay, now i'm a bit hesitating.. there are almost 17 PRs; I can merge them and tag them all simultaneously. But what if something goes wrong...
I want to first fix the "presenting logic" problem in the nimh-minimal repo, then merge these dependabot PRs.
