### ISSUE TITLE
where to define "survey/activity completion and moving on to the next activity"

### ISSUE THREAD

**Issue by yibeichan** [ReproNim/reproschema-ui#320]
The problem I'm having now is from nimh-minimal. 
For example, we need to set up branch logic based on `interview_age` from demographics. The demographics are the first activity in the protocol. Once I set up `isVis` conditions for all other activities in the protocol schema, we can't submit responses from `demographics`. Click `Submit` won't move to the next activity. See [here](https://www.repronim.org/nimh-minimal). I'm testing things so content on this website may change.

So I think there might be somewhere to set up **survey/activity completion and moving on to the next activity**, but all components listed [here](https://github.com/ReproNim/reproschema-ui/tree/master/src/components) have nothing to do with `between survey` setup. [Survey.vue] handles within survey logics.

[router](https://github.com/ReproNim/reproschema-ui/blob/master/src/router/index.js) doesn't do much here either.

I tried to implement some changes in store.js, Landing.vue, see [here](https://github.com/ReproNim/reproschema-ui/compare/master...yibeichan:reproschema-ui:master), instructed by chatgpt (after I repeatedly tells it what the problem is). But we need to dispatch those `actions/methods` to a proper place, such as a place that handles "survey/activity completion and moving on to the next activity", but I don't know where it is.

@satra does it make sense to you? I want to find the component responsible for "activity completion and moving on to the next activity", **between-activities**. do you know I should look at?

**Comment by satra** [comment]
this will require more time than i have right now. i won't be able to check this out for a few days at least. however, take a look at the PR that was merged that allows some of the url parameters to be added when moving from one activity to the next. that may tell you where/when activities are transitioning.

**Comment by satra** [comment]
closed via #323
